FIX: writing ports to site local cfg, edited port env vars out of dev() func, reorganized registration

diff --git a/site-control b/site-control
--- a/site-control
+++ b/site-control
@@ -117,15 +117,19 @@ make_local_config() {
     local site="$1"
     local local_cfg; local_cfg="${PWD}/cfg.yaml"
     touch "$local_cfg"
+    local bport; bport=$(yq e ".sites.${site}.bport" "$REGISTRY")
+    local fport; fport=$(yq e ".sites.${site}.fport" "$REGISTRY")
     read -r -p "Enter site description: " \
-        -i "Webapp to log and view fuel economy data" -e desc
+        -i "Webapp to..." -e desc
     read -r -p "Enter repo URL: " \
-        -i "http://github.com/theHousedev/fuel-log" -e git_url
+        -i "http://github.com/theHousedev/" -e git_url
     yq -i "with(.site;
         .tag = \"${site}\" |
         .name = \"${site^} Log\" |
         .description = \"${desc}\" |
-        .git_repo = \"${git_url}\"
+        .git_repo = \"${git_url}\" |
+        .backend_port = \"${bport}\" |
+        .frontend_port = \"${fport}\"
     )" "${local_cfg}"
     OK "Created local config file: $local_cfg"
 }
@@ -196,17 +200,18 @@ new() {
             esac
         fi
 
-        echo -e "Configuring '$site'..."
-        if ! make_local_config "$site"; then
-            ERR "Failed to create local config; aborting..."
-            exit 1
-        fi
-
+        echo -e "Registering '$site'..."
         if ! register "$site"; then
             ERR "Failed to register site, aborting..."
             exit 1
         else
             OK "Successfully registered site"
+        fi
+
+        echo -e "Configuring '$site'..."
+        if ! make_local_config "$site"; then
+            ERR "Failed to create local config; aborting..."
+            exit 1
         fi
     fi
 }
@@ -239,8 +244,6 @@ dev() {
             echo -e "Found existing tmux session: '${G}$session${NC}'"
         else
             if ! tmux new-session -d -s "$session" \
-                -e "SITE_BACKEND_PORT=$bport" \
-                -e "SITE_FRONTEND_PORT=$fport" \
                 -e "ALLOWED_ORIGIN=http://localhost:$fport" 2>/dev/null; then
                 ERR "Failed to start tmux session."
                 exit 1
